### PR TITLE
fix to config files params: model/model_type

### PR DESCRIPTION
**Pull request by rvinaybharadwaj**

### CODE REVIEW

**Comment by Jodasue** [comment]
Look fine to me... Whats going on with the failed Travis... It looks like some dependency fetch prob.  The line at the end says that it could be intermittent, so I clicked re-run to see if it works.

**Comment by rvinaybharadwaj** [comment]
Not sure about Travis. I made sure tests are passing locally.

**Comment by Jodasue** [comment]
Ok so the tests are now running... but it is giving the following error:
`File "/home/travis/build/exalearn/EXARL/exarl/utils/globals.py", line 113, in lookup_params
    raise ExaGlobals.GlobalDoesNotExist(ExaGlobals.__run_params, key)
exarl.utils.globals.GlobalDoesNotExist: ExaRL globals key does not exist. Trying activation`

**Comment by rvinaybharadwaj** [comment]
I think this is because the CI runs exacartpole and the learner_cfg got modified to a different model_type. Have pushed a fix, let's see if it passes.

**Comment by rvinaybharadwaj** [comment]
OK. CI is passing.

**Review by jmohdyusof — APPROVED** [review]

**Comment by Jodasue** [comment]
Looks good

**Comment by rvinaybharadwaj** [comment]
Please approve, don't close the PR.

**Review by Jodasue — APPROVED** [review]

**Pull request merged**
